### ISSUE TITLE
Use a repr to showcase future annotations

### ISSUE THREAD

**Issue by A5rocks** [python-attrs/cattrs#168]
* cattrs version: 1.7.1
* Python version: 3.9.2
* Operating System: debian 10

### Description

I was (and still am -- I might add another issue here soon :-) investigating an issue with a type not being registered. I *had* registered it though! The problem was that `cattr.errors.StructureHandlerNotFoundError` uses the type's str, instead of its repr:

https://github.com/Tinche/cattrs/blob/5309784280c6e4832c41fcf8e45b58ef4651fc3a/src/cattr/converters.py#L356-L360

### Elaboration
```
2021-09-19:10:57:23,692 ERROR    [shard.py:302] improper payload
Traceback (most recent call last):
  File "/home/a5/oss/bloom/bloom/shard.py", line 289, in _shared_logic
    model: object = data.converter.structure(message['d'], tags_to_model[message['t']])
  File "/home/a5/.cache/pypoetry/virtualenvs/bloom-uo6NeoEe-py3.9/lib/python3.9/site-packages/cattr/converters.py", line 294, in structure
    return self._structure_func.dispatch(cl)(obj, cl)
  File "<cattrs generated structure bloom.models.gateway.ChannelDeleteEvent>", line 3, in structure_ChannelDeleteEvent
    'id': structure_id(o['id'], type_id),
  File "/home/a5/.cache/pypoetry/virtualenvs/bloom-uo6NeoEe-py3.9/lib/python3.9/site-packages/cattr/converters.py", line 360, in _structure_error
    raise StructureHandlerNotFoundError(msg, type_=cl)
cattr.errors.StructureHandlerNotFoundError: Unsupported type: Snowflake. Register a structure hook for it.
```

meanwhile I have this:
```py
    converter.register_structure_hook(
        base_models.Snowflake,
        lambda d, _: base_models.Snowflake(int(d))
    )
```

when I edited the cattrs source and changed it to use the repr of the type instead, here's the log:
```
2021-09-19:10:57:23,692 ERROR    [shard.py:302] improper payload
Traceback (most recent call last):
  File "/home/a5/oss/bloom/bloom/shard.py", line 289, in _shared_logic
    model: object = data.converter.structure(message['d'], tags_to_model[message['t']])
  File "/home/a5/.cache/pypoetry/virtualenvs/bloom-uo6NeoEe-py3.9/lib/python3.9/site-packages/cattr/converters.py", line 294, in structure
    return self._structure_func.dispatch(cl)(obj, cl)
  File "<cattrs generated structure bloom.models.gateway.ChannelDeleteEvent>", line 3, in structure_ChannelDeleteEvent
    'id': structure_id(o['id'], type_id),
  File "/home/a5/.cache/pypoetry/virtualenvs/bloom-uo6NeoEe-py3.9/lib/python3.9/site-packages/cattr/converters.py", line 360, in _structure_error
    raise StructureHandlerNotFoundError(msg, type_=cl)
cattr.errors.StructureHandlerNotFoundError: Unsupported type: 'Snowflake'. Register a structure hook for it.
```

which made the problem much easier to see.

**Comment by Tinche** [comment]
Good idea, will be in the next release.
