### ISSUE TITLE
make_dict_structure_fn fails on NDArray attributes

### ISSUE THREAD

**Issue by larchen** [python-attrs/cattrs#194]
* cattrs version: main from github (ee486051841c11be62b34f7a00c797fded93d5a2)
* attrs version: 21.2.0
* numpy version: 1.21.4
* Python version: 3.9.7
* Operating System: Windows 10

### Description

When creating a structure hook for an attrs class with a `NDArray` field, `make_dict_structure_fn` throws an error. It seems as though the issue stems from trying to copy the type by calling `np.dtype[args]`, because `DType` is a GenericAlias`. Is there a good way of dealing with this?

### What I Did
Minimal steps to reproduce
```python
import numpy as np

from attr import define
from numpy.typing import NDArray
from cattr import GenConverter
from cattr.gen import make_dict_structure_fn

converter = GenConverter()

@define
class A:
    numpy: NDArray

make_dict_structure_fn(A, converter)
```

Traceback:
```
Traceback (most recent call last):
  File "C:\*\test_cattr.py", line 14, in <module>
    make_dict_structure_fn(A, converter)
  File "C:\*\lib\site-packages\cattr\gen.py", line 258, in make_dict_structure_fn
    t = deep_copy_with(t, mapping)
  File "C:\*\lib\site-packages\cattr\generics.py", line 15, in deep_copy_with
    tuple(
  File "C:\*\lib\site-packages\cattr\generics.py", line 18, in <genexpr>
    else (deep_copy_with(a, mapping) if is_generic(a) else a)
  File "C:\*\lib\site-packages\cattr\generics.py", line 13, in deep_copy_with
    return copy_with(
  File "C:\*\lib\site-packages\cattr\_compat.py", line 365, in copy_with
    return type.__origin__[args]
TypeError: 'numpy._DTypeMeta' object is not subscriptable
```

**Comment by Tinche** [comment]
Hmm. I think I can improve our generic handling to make this possible. But dealing with numpy is going to be quite interesting.

Let me get back to you in a few days.

**Comment by Tinche** [comment]
@larchen What are you trying to structure the array from? A list, bytes or something else?

**Comment by larchen** [comment]
I'd like to be able to structure arrays from lists while specifying common dtypes (np.int32, np.float64, np.bool8, etc.) for converting between json/yaml serializable types and numpy.

I currently have a custom hook factory shown below, that works when structuring arrays directly from lists, but the exception above occurs before the converter is even called when I have this within an attrs class.

My hack to get around the error for the time being is to wrap the NDArray type with a `Annotated[NDArray[dtype]]`, which seems to bypass the call to `deep_copy_with` (https://github.com/python-attrs/cattrs/blob/main/src/cattr/gen.py#L257
). But I'm not sure if this has any unintended side effects and I don't like having an unnecessary `Annotated` everywhere.

```
def isndarray(cls):
    return issubclass(get_origin(cls) or cls, np.ndarray)

def get_dtype(cls):
    if not (args := get_args(cls)):
        return None

    _, dtypelike = args

    if dtypelike in get_args(NDArray):
        dtype = None
    else:
        dtype, = get_args(dtypelike)

    if dtype == Any:
        dtype = None

    return dtype

def make_ndarray_structure_fn(cls):
    dtype = get_dtype(cls)
    
    def ndarray_structure_fn(obj, cls):
        if isinstance(obj, np.ndarray):
            if obj.dtype == dtype:
                return obj
            else:
                try:
                    obj.dtype = dtype
                    return  obj
                except ValueError:
                    pass # Copy array if changing dtype in place fails
        return np.array(obj, dtype=dtype)

    return ndarray_structure_fn

def make_ndarray_unstructure_fn(cls):
    return lambda arr: arr.tolist()

converter.register_structure_hook_factory(
    isndarray,
    make_ndarray_structure_fn
)
```

**Comment by Tinche** [comment]
Trying the newly released 1.9, does this snippet help you:
```python
import numpy as np
from attr import define
from numpy.typing import NDArray

from cattr import GenConverter

converter = GenConverter()


@define
class A:
    numpy: NDArray[np.float64]


converter.register_structure_hook_func(
    lambda t: getattr(t, "__origin__", None) is np.ndarray,
    lambda v, t: np.array([t.__args__[1].__args__[0](e) for e in v]),
)
print(converter.structure({"numpy": [1, 2, 3]}, A))

```

**Comment by larchen** [comment]
I still get a similar traceback with this:

```
Traceback (most recent call last):
  File "C:\*\cattr_test.py", line 19, in <module>
    print(converter.structure({"numpy": [1, 2, 3]}, A))
  File "C:\*\lib\site-packages\cattr\converters.py", line 300, in structure
    return self._structure_func.dispatch(cl)(obj, cl)
  File "C:\*\lib\site-packages\cattr\dispatch.py", line 49, in _dispatch
    return self._function_dispatch.dispatch(cl)
  File "C:\*\lib\site-packages\cattr\dispatch.py", line 126, in dispatch
    return handler(typ)
  File "C:\*\lib\site-packages\cattr\converters.py", line 737, in gen_structure_attrs_fromdict
    h = make_dict_structure_fn(
  File "C:\*\lib\site-packages\cattr\gen.py", line 258, in make_dict_structure_fn
    t = deep_copy_with(t, mapping)
  File "C:\*\lib\site-packages\cattr\generics.py", line 15, in deep_copy_with
    tuple(
  File "C:\*\lib\site-packages\cattr\generics.py", line 18, in <genexpr>
    else (deep_copy_with(a, mapping) if is_generic(a) else a)
  File "C:\*\lib\site-packages\cattr\generics.py", line 13, in deep_copy_with
    return copy_with(
  File "C:\*\lib\site-packages\cattr\_compat.py", line 365, in copy_with
    return type.__origin__[args]
```

**Comment by Tinche** [comment]
It works for me, which Python version and which cattrs version are you on?

**Comment by larchen** [comment]
Ah sorry, I was still using the github version from last week — forgot to clear the cache when installing from pip.

This does work now for me with the new 1.9.0 release. Thanks for the help and for this great library!

**Comment by Tinche** [comment]
I think I'll add this to the example usage section.

**Comment by blthayer** [comment]
@Tinche - adding this to the examples in the documentation would still be valuable :smile:

**Comment by Tinche** [comment]
@blthayer Could I persuade you to add it to the usages section in a PR? 😇

**Comment by blthayer** [comment]
Perhaps - I'll see if I can find the time :)
