### ISSUE TITLE
Attrs and underscore attributes

### ISSUE THREAD

**Issue by adrientetar** [python-attrs/cattrs#23]
So attrs has this feature where underscore-prefixed attributes are expected without the underscore in the ctor. But that means `cattr.structure(cattr.unstructure(myinstance), myclass)` will traceback with unexpected keyword argument.

Since cattrs is specifically made to work with attrs, shouldn't it roundtrip underscore-prefixed attributes by default?

**Comment by atugushev** [comment]
@Tinche do you have any idea how to workaround this case? See also #89.

**Comment by Tinche** [comment]
Can you clarify the issue? cattrs works with private attrs attributes, and has for a long time (the OP is from 2017).

**Comment by atugushev** [comment]
@Tinche 

The issue copy-pasted from https://github.com/Tinche/cattrs/issues/89#issue-636023895:

```python
# t.py

import attr
import cattr


@attr.s(auto_attribs=True)
class foo:
    a: str = attr.ib()
    _b: str = attr.ib()


foo(a="a", b="b")
# foo(a='a', _b='b')

cattr.unstructure(foo(a="a", b="b"))
# {'a': 'a', '_b': 'b'}

# This somehow works despite the init for foo() looking for `b` not `_b`
cattr.structure({"a": "a", "_b": "b"}, foo)
# foo(a='a', _b='b')

# But this fails because cattr fails to pass `b` into the __init__ function
cattr.structure({"a": "a2", "b": "b2"}, foo)
```

Traceback is:

```console
$ python t.py
Traceback (most recent call last):
  File "t.py", line 22, in <module>
    cattr.structure({"a": "a2", "b": "b2"}, foo)
  File "/private/var/folders/4x/rz_w89dx1z3bydfd6qpdjn_h0000gn/T/tmp.QVcREd50/.venv/lib/python3.8/site-packages/cattr/converters.py", line 199, in structure
    return self._structure_func.dispatch(cl)(obj, cl)
  File "/private/var/folders/4x/rz_w89dx1z3bydfd6qpdjn_h0000gn/T/tmp.QVcREd50/.venv/lib/python3.8/site-packages/cattr/converters.py", line 339, in structure_attrs_fromdict
    return cl(**conv_obj)  # type: ignore
TypeError: __init__() missing 1 required positional argument: 'b'
```

**Comment by Tinche** [comment]
Ah, you want the unstructured data to not match the class? You can customize using the new `GenConverter`.

```
import attr

import cattr
from cattr.gen import make_dict_structure_fn, make_dict_unstructure_fn


@attr.define
class foo:
    a: str = attr.ib()
    _b: str = attr.ib()


foo(a="a", b="b")

c = cattr.GenConverter()
c.register_structure_hook(
    foo, make_dict_structure_fn(foo, c, _b=cattr.override(rename="b"))
)
c.register_unstructure_hook(
    foo, make_dict_unstructure_fn(foo, c, _b=cattr.override(rename="b"))
)

print(c.unstructure(foo(a="a", b="b")))

print(c.structure({"a": "a2", "b": "b2"}, foo))
```

**Comment by atugushev** [comment]
@Tinche 

Oh, wonderful! Thank you so much for the quick response 🙏🏼
