### ISSUE TITLE
cattrs is not compatible with type hints from python 3.10 in python 3.8

### ISSUE THREAD

**Issue by quarckster** [python-attrs/cattrs#270]
* cattrs version: 22.1.0
* Python version: 3.8.10
* Operating System: Linux

### Description

`cattrs` fails to structure an object with  `from __future__ import annotations` on Python 3.8

### Reproducer
Run this code on Python 3.8.10

```python
from __future__ import annotations

import attrs
import cattrs

unstructured = {"a": 1}

@attrs.define
class Test:
    a: str | None = None

cattrs.structure(unstructured, Test)
```

Traceback:

```
Traceback (most recent call last):
  File "/tmp/test.py", line 13, in <module>
    cattrs.structure(unstructured, Test)
  File "/home/user/venvs/test/lib/python3.8/site-packages/cattrs/converters.py", line 281, in structure
    return self._structure_func.dispatch(cl)(obj, cl)
  File "/home/user/venvs/test/lib/python3.8/site-packages/cattr/dispatch.py", line 49, in _dispatch
    return self._function_dispatch.dispatch(cl)
  File "/home/user/venvs/test/lib/python3.8/site-packages/cattr/dispatch.py", line 122, in dispatch
    return handler(typ)
  File "/home/user/venvs/test/lib/python3.8/site-packages/cattrs/converters.py", line 753, in gen_structure_attrs_fromdict
    resolve_types(cl)
  File "/home/user/venvs/test/lib/python3.8/site-packages/attr/_funcs.py", line 412, in resolve_types
    hints = typing.get_type_hints(cls, globalns=globalns, localns=localns)
  File "/usr/lib/python3.8/typing.py", line 1232, in get_type_hints
    value = _eval_type(value, base_globals, localns)
  File "/usr/lib/python3.8/typing.py", line 270, in _eval_type
    return t._evaluate(globalns, localns)
  File "/usr/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

### Additional info

`mypy` doesn't find any issues:

```
mypy /tmp/test.py 
Success: no issues found in 1 source file
```

**Comment by Tinche** [comment]
Hi,

you can't use the new union syntax in a runtime context on pre-3.10 Pythons (Mypy works since Mypy doesn't actually evaluate the code, but cattrs must evaluate it). It's not something we can fix in cattrs, unfortunately. You can switch to using `Union` instead, or upgrade to 3.10+.
