### ISSUE TITLE
NewType support broken by recent `functools.singledispatch` changes

### ISSUE THREAD

**Issue by bkurtz** [python-attrs/cattrs#297]
* cattrs version: main (290d162a589acf10ea63b825b7b283e23ca7698a)
* Python version: 3.9.10
* Operating System: macOS 12.5.1

### Description

NewType support was recently added in #255 (see also #94), but appears to have been broken by recent changes to `functools.singledispatch` that landed in recent pythons (see, e.g. #206, maybe #216).

Aspirationally, something like this should work:
```python
IsoDate = NewType("IsoDate", dt.datetime)
conv.register_structure_hook(IsoDate, ...)
```

### What I Did
python 3.9.10 venv:
```
Python 3.9.10 (main, Jan 15 2022, 11:48:15) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime as dt
>>> from typing import NewType
>>> import cattrs
>>> conv = cattrs.Converter()
>>> IsoDate = NewType("IsoDate", dt.datetime)
>>> conv.register_structure_hook(IsoDate, lambda s, _: IsoDate(dt.datetime.fromisoformat(s)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/ctest/lib/python3.9/site-packages/cattrs/converters.py", line 254, in register_structure_hook
    self._structure_func.register_cls_list([(cl, func)])
  File "/private/tmp/ctest/lib/python3.9/site-packages/cattrs/dispatch.py", line 57, in register_cls_list
    self._single_dispatch.register(cls, handler)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/functools.py", line 855, in register
    raise TypeError(
TypeError: Invalid first argument to `register()`. <function NewType.<locals>.new_type at 0x1025a4c10> is not a class.
```
python 3.8.9 (because that's the other one I had handy) venv:
```
Python 3.8.9 (default, Mar 30 2022, 13:51:17) 
[Clang 13.1.6 (clang-1316.0.21.2.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime as dt
>>> from typing import NewType
>>> import cattrs
>>> conv = cattrs.Converter()
>>> IsoDate = NewType("IsoDate", dt.datetime)
>>> conv.register_structure_hook(IsoDate, lambda s, _: IsoDate(dt.datetime.fromisoformat(s)))
>>> conv.structure("2022-01-01", IsoDate)
datetime.datetime(2022, 1, 1, 0, 0)
```
(also tested this in `python:3.9.9-alpine` docker image and get similar results to 3.8.9.)

Not sure what the best strategy for this in `cattrs` would be, but going to be doing some working around it for our local project this week, and if it were easy I might be talked into opening a PR here too.

FWIW, the other common case we're having issues with is generics (related to #216).

**Comment by Tinche** [comment]
So before we go any further, can you check on 3.10? According to the docs (https://docs.python.org/3/library/typing.html#newtype) in 3.10+ NewType will produce a class, not a function.

**Comment by bkurtz** [comment]
Unfortunately, looks like it's still not helpful:
```
Python 3.10.4 (main, Mar 29 2022, 13:56:05) [GCC 10.3.1 20211027] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime as dt
>>> from typing import NewType
>>> import cattrs
>>> conv = cattrs.Converter()
>>> IsoDate = NewType("IsoDate", dt.datetime)
>>> conv.register_structure_hook(IsoDate, lambda s, _: IsoDate(dt.datetime.fromisoformat(s)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/cattrs/converters.py", line 254, in register_structure_hook
    self._structure_func.register_cls_list([(cl, func)])
  File "/usr/local/lib/python3.10/site-packages/cattrs/dispatch.py", line 57, in register_cls_list
    self._single_dispatch.register(cls, handler)
  File "/usr/local/lib/python3.10/functools.py", line 856, in register
    raise TypeError(
TypeError: Invalid first argument to `register()`. __main__.IsoDate is not a class.
>>> type(IsoDate)
<class 'typing.NewType'>
```

**Comment by Tinche** [comment]
Would be great if you gave https://github.com/python-attrs/cattrs/pull/310 a try in the next couple of days, then I can cut a release.

**Comment by Tinche** [comment]
Sorry, closed by accident.

**Comment by bkurtz** [comment]
Tried out #310 and it seems to work well.  Thanks for adding!

**Comment by Tinche** [comment]
Thanks for checking. Closing this now.
