### ISSUE TITLE
A `null` value in a json object is unexpectedly rendered as the string `'None'` when structuring to a `typing.Dict[str, str]` instead of failing.

### ISSUE THREAD

**Issue by cuyt** [python-attrs/cattrs#316]
* cattrs version: 22.1.0
* Python version: 3.8.13
* Operating System: Windows 10

### Description

Aim: I'm structuring a json object to a python dict with typedef `typing.Dict[str, str]`.

Expected: I expect that structuring fails if a `null` is encountered as a json dict value.

Observed: The `null` value in the json string is rendered as a string `'None'` in the structured dict object and structuring succeeds.

### What I Did

```python
from cattrs.preconf.json import make_converter
from typing import Dict, Any

c = make_converter()

json_string = """
{
  "this" : null    
}"""

d = c.loads(json_string, Dict[str, Any]) # Works as expected when values can be any type by rendering null as None
print(d)

d = c.loads(json_string, Dict[str, str]) # I'd expect this to fail instead of rendering null as the string 'None'
print(d) 

c.loads(json_string, Dict[str, int]) # Fails as expected when the value type is int
```

Only the last line fails, but I would expect the second `c.loads` to fail analogously. 

```
{'this': None}
{'this': 'None'}
---------------------------------------------------------------------------
IterableValidationError                   Traceback (most recent call last)
...-cattrs-testing.ipynb Cell 1 in <cell line: 17>()
     [14]... cattrs-testing.ipynb#W2sZmlsZQ%3D%3D?line=13) d = c.loads(json_string,Dict[str,str])
     [15... cattrs-testing.ipynb#W2sZmlsZQ%3D%3D?line=14) print(d)
---> [17]... cattrs-testing.ipynb#W2sZmlsZQ%3D%3D?line=16) c.loads(json_string,Dict[str,int])

File ... \site-packages\cattr\preconf\json.py:19, in JsonConverter.loads(self, data, cl, **kwargs)
     18 def loads(self, data: Union[bytes, str], cl: Type[T], **kwargs) -> T:
---> 19     return self.structure(loads(data, **kwargs), cl)

File ... \site-packages\cattrs\converters.py:281, in Converter.structure(self, obj, cl)
    278 def structure(self, obj: Any, cl: Type[T]) -> T:
    279     """Convert unstructured Python data structures to structured data."""
--> 281     return self._structure_func.dispatch(cl)(obj, cl)

File :17, in structure_mapping(mapping, _)

IterableValidationError: While structuring typing.Dict[str, int] (1 sub-exception)
```

How can I prevent `null` values from being rendered as string and hence accepted as input for structuring dict values with type `str` or is my expectation unfounded?

**Comment by Tinche** [comment]
Hi,

cattrs does coercion by default, since it's faster and helps with compatibility with some of the libraries. So what cattrs will do by default is call `str(None)` on your value, which in Python produces the string `'None'`.

What you want to do is override how the `str` type is structured. Like this:

```python
from cattrs.preconf.json import make_converter
from typing import Dict, Any

c = make_converter()

def structure_string(val, _):
    if not isinstance(val, str):
        raise TypeError(f'{val} is not a string')
    return val

c.register_structure_hook(str, structure_string)
```
This will produce:
```
  + Exception Group Traceback (most recent call last):
  |   File "/Users/tintvrtkovic/pg/cattrs/a07.py", line 21, in <module>
  |     d = c.loads(json_string, Dict[str, str])
  |   File "/Users/tintvrtkovic/pg/cattrs/src/cattrs/preconf/json.py", line 19, in loads
  |     return self.structure(loads(data, **kwargs), cl)
  |   File "/Users/tintvrtkovic/pg/cattrs/src/cattrs/converters.py", line 309, in structure
  |     return self._structure_func.dispatch(cl)(obj, cl)
  |   File "", line 17, in structure_mapping
  | cattrs.errors.IterableValidationError: While structuring typing.Dict[str, str] (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "", line 5, in structure_mapping
    |   File "/Users/tintvrtkovic/pg/cattrs/a07.py", line 10, in structure_string
    |     raise TypeError(f"{val} is not a string")
    | TypeError: None is not a string
    | Structuring mapping value @ key 'this'
    +------------------------------------
```
Many types can have overriden hooks like this ;)

That said, I've had repeating requests for easy ways to disable coercion for primitive values, so it's happening in the next version.

**Comment by cuyt** [comment]
Thanks for the quick reply and the solution for my specific problem. The rationale that it helps with interoperability and speed is perfectly acceptable to me. Nonetheless, it's great that the ability to easily and transparently opt out of coercion will be available from the next version!
