### ISSUE TITLE
22.2.0: `cattrs` still uses `setuptools

### ISSUE THREAD

**Issue by kloczek** [python-attrs/cattrs#356]
Looks like despite move to `poetry-core` as pep517 build backed `cattrs` still uses `setuptools` on building documentation.
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v6.2.0

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 354, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/tkloczko/rpmbuild/BUILD/cattrs-22.2.0/docs/conf.py", line 19, in <module>
    import pkg_resources  # part of setuptools
ModuleNotFoundError: No module named 'pkg_resources'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 207, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 177, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 367, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 354, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/tkloczko/rpmbuild/BUILD/cattrs-22.2.0/docs/conf.py", line 19, in <module>
    import pkg_resources  # part of setuptools
ModuleNotFoundError: No module named 'pkg_resources'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 354, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/tkloczko/rpmbuild/BUILD/cattrs-22.2.0/docs/conf.py", line 19, in <module>
    import pkg_resources  # part of setuptools
```

**Comment by Tinche** [comment]
Hi,

I think this is already fixed on main, can you check for me?

**Comment by Tinche** [comment]
Couldn't repro, reopen if still an issue on main!
