### ISSUE TITLE
Structure with an attribute which is a list of Self

### ISSUE THREAD

**Issue by ares-b** [python-attrs/cattrs#359]
* cattrs version: 22.2.0
* Python version: 3.8.10
* Operating System: Ubuntu 22.04

### Description

Cattrs cannot structure My Class if  one of my attributes type is a List of the `self` type.
### What I Did

```
import attrs
import cattrs
from typing import List
@attrs.define
class A:
    x: int = attrs.field(validator=attrs.validators.instance_of(int))
    y: str = attrs.field(validator=attrs.validators.instance_of(str))
    z: "List[A]" = attrs.field(validator=attrs.validators.deep_iterable(
        member_validator=attrs.validators.instance_of("A"),
        iterable_validator=attrs.validators.instance_of(list),
    ))



@attrs.define
class MyClass:
    test: A = attrs.field(validator=attrs.validators.instance_of(A))

m = cattrs.structure({"test":  {"x": 3, "y": "ok", "z": [{"x": 3, "y": "ok"}]}}, MyClass) # Works
```

Throws:
```
File "<cattrs generated structure __main__.MyClass>", line 9, in structure_MyClass
cattrs.errors.ClassValidationError: While structuring MyClass (1 sub-exception)
```

**Comment by Tinche** [comment]
Howdy.

Might be connected to our handling of `ForwardRefs`. I'll take a look when I catch a moment.

**Comment by Tinche** [comment]
@ares-b so I looked into this.

If you run this piece of code on 3.11, you'll get a better stack trace (I guess the `exceptiongroup` backport on 3.8 doesn't show nice stack traces by default).

Here's the trace:
```
❯ python a08.py
  + Exception Group Traceback (most recent call last):
  |   File "/home/tin/pg/cattrs/a08.py", line 20, in <module>
  |     m = cattrs.structure(
  |         ^^^^^^^^^^^^^^^^^
  |   File "/home/tin/pg/cattrs/src/cattrs/converters.py", line 334, in structure
  |     return self._structure_func.dispatch(cl)(obj, cl)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "<cattrs generated structure __main__.MyClass>", line 9, in structure_MyClass
  | cattrs.errors.ClassValidationError: While structuring MyClass (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "<cattrs generated structure __main__.MyClass>", line 5, in structure_MyClass
    |   File "<cattrs generated structure __main__.A>", line 19, in structure_A
    | cattrs.errors.ClassValidationError: While structuring A (1 sub-exception)
    | Structuring class MyClass @ attribute test
    +-+---------------- 1 ----------------
      | Exception Group Traceback (most recent call last):
      |   File "<cattrs generated structure __main__.A>", line 15, in structure_A
      |   File "/home/tin/pg/cattrs/src/cattrs/converters.py", line 545, in _structure_list
      |     raise IterableValidationError(
      | cattrs.errors.IterableValidationError: While structuring typing.List[__main__.A] (1 sub-exception)
      | Structuring class A @ attribute z
      +-+---------------- 1 ----------------
        | Exception Group Traceback (most recent call last):
        |   File "/home/tin/pg/cattrs/src/cattrs/converters.py", line 535, in _structure_list
        |     res.append(handler(e, elem_type))
        |                ^^^^^^^^^^^^^^^^^^^^^
        |   File "<cattrs generated structure __main__.A>", line 19, in structure_A
        | cattrs.errors.ClassValidationError: While structuring A (1 sub-exception)
        | Structuring typing.List[__main__.A] @ index 0
        +-+---------------- 1 ----------------
          | Traceback (most recent call last):
          |   File "<cattrs generated structure __main__.A>", line 15, in structure_A
          | KeyError: 'z'
          | Structuring class A @ attribute z
          +------------------------------------
```
What this stack trace is saying, an instance of `A` doesn't have the `z` attribute. And that's true, in your code snippet, the `A` in the list is `{"x": 3, "y": "ok"}`. This won't work since the `z` attribute has no default value. If you add a value for `z`, it works.

```
m = cattrs.structure(
    {"test": {"x": 3, "y": "ok", "z": [{"x": 3, "y": "ok", "z": []}]}}, MyClass
)
```
