### ISSUE TITLE
Structuring fails with PEP 695 aliases to Literal

### ISSUE THREAD

**Issue by Fuyukai** [python-attrs/cattrs#484]
* cattrs version: git main d7f6d6f
* Python version: 3.12.1
* Operating System: linux

### Description

Structuring a class with a ``type Lit = Literal[...]``

### What I Did

```
from typing import Literal

import attr
import cattr

type BootlegEnum = Literal[1, 2, 3]

@attr.s()
class UsesBootlegEnum:  # noqa: D101
    tag: BootlegEnum = attr.ib()


cattr.structure({"tag": 1}, UsesBootlegEnum)
```

```
  + Exception Group Traceback (most recent call last):
  |   File "test.py", line 13, in <module>
  |     cattr.structure({"tag": 1}, UsesBootlegEnum)
  |   File ".venv/lib/python3.12/site-packages/cattrs/converters.py", line 346, in structure
  |     return self._structure_func.dispatch(cl)(obj, cl)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "<cattrs generated structure __main__.UsesBootlegEnum>", line 9, in structure_UsesBootlegEnum
  | cattrs.errors.ClassValidationError: While structuring UsesBootlegEnum (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "<cattrs generated structure __main__.UsesBootlegEnum>", line 5, in structure_UsesBootlegEnum
    |   File ".venv/lib/python3.12/site-packages/cattrs/converters.py", line 467, in _structure_simple_literal
    |     if val not in type.__args__:
    |                   ^^^^^^^^^^^^^
    | AttributeError: 'typing.TypeAliasType' object has no attribute '__args__'. Did you mean: '__ror__'?
    | Structuring class UsesBootlegEnum @ attribute tag
    +------------------------------------
```

**Comment by Tinche** [comment]
Oh interesting, good catch. Let me see if I can get this into a patch release.

**Comment by Tinche** [comment]
Ah sorry, I see you're on main. I forgot the type alias support is only in 24.1 which is unreleased as of yet. I will just fix this on main.

**Comment by Fuyukai** [comment]
Works perfectly. Thanks for the quick fix.
