### ISSUE TITLE
Passthrough nested attrs instances when structuring

### ISSUE THREAD

**Issue by delfick** [python-attrs/cattrs#608]
* cattrs version: 24.1.2
* Python version: 3.13
* Operating System: Mac

### Description

I want cattrs to not restructure an attrs instance that's already the correct type.

For example

```python
import attrs
import cattrs


@attrs.frozen
class A:
    a: int
    b: str


@attrs.frozen
class B:
    c: bool
    d: list[int]


@attrs.frozen
class C:
    one: int
    two: A
    three: B


data = {"one": 10, "two": {"a": 10, "b": "asdf"}, "three": B(c=True, d=[1, 2])}
got = cattrs.structure(data, C)
```

Results in

```
╰─ python a.py
  + Exception Group Traceback (most recent call last):
  |   File "/Users/stephenm/Projects/my-project/a.py", line 25, in <module>
  |     got = cattrs.structure(data, C)
  |   File "/Users/stephenm/Projects/my-project/.venv/lib/python3.13/site-packages/cattrs/converters.py", line 558, in structure

  |     return self._structure_func.dispatch(cl)(obj, cl)
  |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  |   File "<cattrs generated structure __main__.C>", line 19, in structure_C
  |     if errors: raise __c_cve('While structuring ' + 'C', errors, __cl)
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | cattrs.errors.ClassValidationError: While structuring C (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "<cattrs generated structure __main__.C>", line 15, in structure_C
    |     res['three'] = __c_structure_three(o['three'], __c_type_three)
    |                    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "<cattrs generated structure __main__.B>", line 14, in structure_B
    |     if errors: raise __c_cve('While structuring ' + 'B', errors, __cl)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | cattrs.errors.ClassValidationError: While structuring B (2 sub-exceptions)
    | Structuring class C @ attribute three
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "<cattrs generated structure __main__.B>", line 5, in structure_B
      |     res['c'] = __c_structure_c(o['c'])
      |                                ~^^^^^
      | TypeError: 'B' object is not subscriptable
      | Structuring class B @ attribute c
      +---------------- 2 ----------------
      | Traceback (most recent call last):
      |   File "<cattrs generated structure __main__.B>", line 10, in structure_B
      |     res['d'] = __c_structure_d(o['d'], __c_type_d)
      |                                ~^^^^^
      | TypeError: 'B' object is not subscriptable
      | Structuring class B @ attribute d
      +------------------------------------
```

Is there an option that makes cattrs not restructure attrs objects that are already the correct type? or do I need to create some custom hook?

**Comment by Tinche** [comment]
You can create a hook or a hook factory. Do you want this behavior only for `B` or for all attrs classes?

**Comment by delfick** [comment]
@Tinche I'd love it for all attrs classes.

In my project where I'm doing this I happen to know the specific attributes that are always gonna be instances and I do this for a few specific classes.

```python
def structure_raw_command(
    val: cattrs.dispatch.UnstructuredValue, target: cattrs.dispatch.TargetType
) -> RawCommand:
    if isinstance(val, RawCommand):
        return val

    raise ValueError("Expected RawCommand")

def function_that_creates_converter_for_specific_situation(self) -> cattrs.Converter:
    converter = cattrs.Converter()
    converter.register_structure_hook(RawCommand, structure_raw_command)
    return converter
```

but it feels like bad coupling to me.

**Comment by Tinche** [comment]
You can intercept the structure hook factory for attrs classes like this:
```python
from attrs import has

from cattrs import Converter
from cattrs.gen import make_dict_structure_fn

converter = Converter()


@converter.register_structure_hook_factory(has)
def my_attrs_hook_factory(cls: type, converter: Converter):
    base_hook = make_dict_structure_fn(cls, converter)

    return base_hook
```

So now we can wrap the default hook in any way we like. In your case, it might look something like:

```python
from collections.abc import Callable, Mapping
from typing import Any, TypeVar

from attrs import AttrsInstance, has

from cattrs import Converter
from cattrs.gen import make_dict_structure_fn

converter = Converter()

T = TypeVar("T", bound=AttrsInstance)


@converter.register_structure_hook_factory(has)
def my_attrs_hook_factory(
    cls: type[T], converter: Converter
) -> Callable[[Mapping, Any], T]:
    base_hook = make_dict_structure_fn(cls, converter)

    def checking_hook(val: Mapping, cls: type[T] = cls) -> T:
        if isinstance(val, cls):
            return val
        return base_hook(val, cls)

    return checking_hook
```

The new hook just does an `isinstance` call and if it's false, delegates to the default hook.

**Comment by delfick** [comment]
@Tinche perfect, thanks!!!
